DROP USER IF EXISTS __DB_NAME__;
DROP DATABASE IF EXISTS __DB_NAME__;
CREATE DATABASE __DB_NAME__;
CREATE USER '__DB_USER__'@'%' IDENTIFIED BY '__DB_PASSWORD__';
GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__DB_USER__'@'%';

FLUSH PRIVILEGES;
USE __DB_NAME__;
