DROP USER IF EXISTS __DB_NAME__;
DROP DATABASE IF EXISTS __DB_NAME__;
CREATE DATABASE __DB_NAME__;
CREATE USER '__DB_NAME__'@'%' IDENTIFIED BY '__DB_USER__';
GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__DB_NAME__'@'%';

FLUSH PRIVILEGES;
USE __DB_NAME__;
