DROP USER IF EXISTS __SERVICE_NAME__;
DROP DATABASE IF EXISTS __SERVICE_NAME__;
CREATE DATABASE __SERVICE_NAME__;
CREATE USER '__SERVICE_NAME__'@'%' IDENTIFIED BY '__DB_USER__';
GRANT ALL PRIVILEGES ON __SERVICE_NAME__.* TO '__SERVICE_NAME__'@'%';

FLUSH PRIVILEGES;
USE __SERVICE_NAME__;
