CREATE TABLE `user_companies` (
    `id` INT AUTO_INCREMENT,
    `user_id` INT NOT NULL DEFAULT 0,
    `name` VARCHAR(80) NOT NULL DEFAULT '',
    `description` VARCHAR(1000) NOT NULL DEFAULT '',
    `address1` varchar(500) DEFAULT '',
    `address2` varchar(500) DEFAULT '',
    `city` varchar(200) DEFAULT '',
    `state_province` varchar(200) NOT NULL DEFAULT '',
    `country` varchar(200) DEFAULT '',
    `country_code` varchar(2) DEFAULT '',
    `postal_code` varchar(100) DEFAULT '',
    `website` VARCHAR(1000) NOT NULL DEFAULT '',
    `data` JSON NULL,
    `active` INT NOT NULL DEFAULT 1,
    `updated_at` DATETIME NOT NULL DEFAULT NOW(),
    `update_user_id` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT NOW(),
    `create_user_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    KEY `user_id` (`user_id`),
    CONSTRAINT `user_companies_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
